name: Release

on:
  release:
    types: [created]

jobs:
  PyPI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install setuptools
        python3 -m pip install --upgrade pip
        python3 -m pip install -r ./requirements.txt
        python3 -m pip install -r ./requirements.dev.txt
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*