name: Tag

on:
  push:
    tag:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '13.x'
      - run: |
          git fetch --prune --unshallow --tags
          git config --global user.name "St. Jude Cloud"
          git config --global user.email "support@stjude.cloud"
      - run: npm install -g conventional-github-releaser
      - run: conventional-github-releaser -p angular
        env:
            DEBUG: conventional-github-releaser
            CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.GITHUB_TOKEN }}